import{i as c,S as d}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&e(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function e(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();function u(o){return fetch(`https://pixabay.com/api/?key=44710644-2154e124280f212c40f530ba7&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).catch(e=>{c.error({position:"topRight",message:`An error occurred: ${e.message}`})})}const p=new d(".gallery-list a",{captions:!0,captionsData:"alt",captionsDelay:250});function h(o){const s=document.querySelector(".gallery-list");let a=o.hits.map(e=>`<div class="image-wrapper">
    <a href="${e.largeImageURL}">
    <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}"></img>
    </a>
    <div class="text-wrapper">
    <div class="text-item"><h5 class="text-header">Likes</h5><p class="text-paragraph">${e.likes}</p></div>
    <div class="text-item"><h5 class="text-header">Views</h5><p class="text-paragraph">${e.views}</p></div>
    <div class="text-item"><h5 class="text-header">Comments</h5><p class="text-paragraph">${e.comments}</p></div>
    <div class="text-item"><h5 class="text-header">Downloads</h5><p class="text-paragraph">${e.downloads}</p></div>
    </div>
    </div>`).join("");s.insertAdjacentHTML("beforeend",a),p.refresh()}function m(){const o=document.querySelector(".gallery-list");o.innerHTML=""}const l=document.querySelector(".form-gallery"),f=document.querySelector(".form-gallery-input"),n=document.querySelector(".loader");l.addEventListener("submit",g);function g(o){o.preventDefault(),m(),n.classList.remove("hidden");let s=f.value.trim();u(`${s}`).then(a=>{if(a.total===0||s===""){c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}else h(a),l.reset()}).finally(()=>{n.classList.add("hidden")})}
//# sourceMappingURL=commonHelpers.js.map
